/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITreasury__factory } from "./ITreasury__factory";
export { InvestmentGateway__factory } from "./InvestmentGateway__factory";
