/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as couponDistributorSol from "./CouponDistributor.sol";
export type { couponDistributorSol };
import type * as investmentGatewaySol from "./InvestmentGateway.sol";
export type { investmentGatewaySol };
import type * as swapGatewaySol from "./SwapGateway.sol";
export type { swapGatewaySol };
import type * as treasurySwapSol from "./TreasurySwap.sol";
export type { treasurySwapSol };
export type { IdentityRegistry } from "./IdentityRegistry";
export type { IdentityRegistryV2 } from "./IdentityRegistryV2";
export type { MockRouter } from "./MockRouter";
export type { MockUSDT } from "./MockUSDT";
export type { SovereignBond } from "./SovereignBond";
