/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasurySwap,
  ITreasurySwapInterface,
} from "../../../contracts/SwapGateway.sol/ITreasurySwap";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
    ],
    name: "buyFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITreasurySwap__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasurySwapInterface {
    return new Interface(_abi) as ITreasurySwapInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasurySwap {
    return new Contract(address, _abi, runner) as unknown as ITreasurySwap;
  }
}
