/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISovereignBond,
  ISovereignBondInterface,
} from "../../../contracts/CouponDistributor.sol/ISovereignBond";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISovereignBond__factory {
  static readonly abi = _abi;
  static createInterface(): ISovereignBondInterface {
    return new Interface(_abi) as ISovereignBondInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISovereignBond {
    return new Contract(address, _abi, runner) as unknown as ISovereignBond;
  }
}
